# Generated by Django 6.0.6 on 2026-06-19 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otprecord_alter_user_is_active'),
        ('booking', '0002_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatenessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], help_text='Role of the person filing the report.', max_length=10)),
                ('delay_range', models.CharField(choices=[('5_15min', '5–15 Minutes'), ('15_30min', '15–30 Minutes'), ('30_plus', '30+ Minutes'), ('no_show', 'No Show')], help_text='How late was the other party?', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the lateness / no-show incident.')),
                ('admin_action', models.CharField(choices=[('pending', 'Pending'), ('no_action', 'No Action'), ('warning', 'Warning Issued'), ('fined', 'Fined'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='pending', help_text='Admin action taken on this report. Default: pending.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_against', models.ForeignKey(help_text='The user being reported.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='The user who filed this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The session this report is about.', on_delete=django.db.models.deletion.CASCADE, related_name='lateness_reports', to='booking.session')),
            ],
            options={
                'verbose_name': 'Lateness Report',
                'verbose_name_plural': 'Lateness Reports',
                'db_table': 'lateness_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason provided by the student for the reschedule request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the reschedule request.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='The booking for which reschedule is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='booking.booking')),
                ('requested_by', models.ForeignKey(help_text='The student requesting reschedule.', on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Reschedule Request',
                'verbose_name_plural': 'Reschedule Requests',
                'db_table': 'reschedule_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
