# Generated by Django 6.0.6 on 2026-06-22 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('payment_confirmed', 'Payment Confirmed'), ('session_reminder', 'Session Reminder'), ('report_filed', 'Report Filed'), ('warning_issued', 'Warning Issued'), ('fine_applied', 'Fine Applied'), ('payout_released', 'Payout Released'), ('suspension_notice', 'Suspension Notice'), ('tutor_approved', 'Tutor Approved'), ('tutor_rejected', 'Tutor Rejected'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
            },
        ),
    ]
