# Generated by Django 6.0.6 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('payment_confirmed', 'Payment Confirmed'), ('session_reminder', 'Session Reminder'), ('report_filed', 'Report Filed'), ('warning_issued', 'Warning Issued'), ('fine_applied', 'Fine Applied'), ('payout_released', 'Payout Released'), ('suspension_notice', 'Suspension Notice'), ('tutor_approved', 'Tutor Approved'), ('tutor_rejected', 'Tutor Rejected'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
