# Generated by Django 6.0.6 on 2026-06-16 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otprecord_alter_user_is_active'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Overall rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text='Written feedback from the student.')),
                ('knowledge_rating', models.IntegerField(blank=True, help_text='Subject knowledge rating (1–5, optional).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teaching_rating', models.IntegerField(blank=True, help_text='Teaching style rating (1–5, optional).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication skills rating (1–5, optional).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.IntegerField(blank=True, help_text='Punctuality rating (1–5, optional).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(help_text='The completed booking this review belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.booking')),
                ('student', models.ForeignKey(help_text='The student who wrote this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='accounts.student')),
                ('tutor', models.ForeignKey(help_text='The tutor being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.tutor')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
