# Generated by Django 6.0.6 on 2026-06-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otprecord_alter_user_is_active'),
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged to student (NPR). Equals tutor pricing_per_session.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current payment state.', max_length=10)),
                ('esewa_ref_id', models.CharField(blank=True, help_text='Transaction reference ID returned by eSewa on success.', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed by eSewa.', null=True)),
                ('booking', models.OneToOneField(help_text='The booking this payment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid by student (NPR). Source of all calculations.', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform commission = total_paid * 0.30', max_digits=10)),
                ('tutor_base_share', models.DecimalField(decimal_places=2, help_text='Tutor base share = total_paid * 0.70', max_digits=10)),
                ('fine_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine percentage applied to tutor base share (e.g. 0.20 = 20%).', max_digits=5)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount = tutor_base_share * fine_percentage.', max_digits=10)),
                ('fine_reason', models.CharField(blank=True, help_text='Admin-provided reason for the fine.', max_length=500, null=True)),
                ('student_refund', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to refund to student. Equals fine_amount per schema.', max_digits=10)),
                ('tutor_final_payout', models.DecimalField(decimal_places=2, help_text='Net payout to tutor = tutor_base_share - fine_amount.', max_digits=10)),
                ('payout_status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('fined', 'Fined')], default='held', help_text='Current payout state. Admin must explicitly release.', max_length=10)),
                ('released_at', models.DateTimeField(blank=True, help_text='Timestamp when payout was released by admin.', null=True)),
                ('booking', models.OneToOneField(help_text='The booking this payout is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='booking.booking')),
                ('fine_imposed_by', models.ForeignKey(blank=True, help_text='Admin user who imposed the fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_imposed', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, help_text='Admin user who released the payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_released', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(help_text='The tutor receiving this payout.', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.tutor')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payout',
                'ordering': ['-id'],
            },
        ),
    ]
