# Generated by Django 6.0.6 on 2026-06-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_otprecord_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_or_skill', models.CharField(help_text='The subject or skill the student wants to learn.', max_length=255)),
                ('proposed_date', models.DateField(help_text='The date proposed by the student for the session.')),
                ('proposed_start_time', models.TimeField(help_text='Proposed session start time.')),
                ('proposed_end_time', models.TimeField(help_text='Proposed session end time.')),
                ('message', models.TextField(blank=True, default='', help_text='Optional message from the student to the tutor.')),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking.', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason provided by the tutor when rejecting the booking.')),
                ('officially_scheduled', models.BooleanField(default=False, help_text='Set to True ONLY after eSewa payment is confirmed (Phase 5). Must remain False throughout Phase 4.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_slot', models.ForeignKey(blank=True, help_text='Optional reference to the tutor availability slot selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.tutoravailability')),
                ('student', models.ForeignKey(help_text='The student who made the booking request.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.student')),
                ('tutor', models.ForeignKey(help_text='The tutor who received the booking request.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='accounts.tutor')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
