# Generated by Django 6.0.6 on 2026-06-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='The date and time when this session is scheduled to start.')),
                ('tutor_start_time', models.DateTimeField(blank=True, help_text='The exact time the tutor started the session.', null=True)),
                ('session_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the session.', max_length=10)),
                ('officially_scheduled', models.BooleanField(default=False, help_text='Set to True only after eSewa payment is completed (Phase 5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='The booking associated with this session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'session',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
